### ISSUE TITLE
MAX_STRING_SIZE vs MAX_STRING_SIZE+1?

### ISSUE THREAD

**Issue by anjohnson** [EPICSTools/ether_ip#11]
I am in the process of adding ether_ip device support for the 3.15+ lsi/lso (long string in/out) record types (a PR will be forthcoming soon), and I notice that the existing stringout device support code uses `MAX_STRING_SIZE` for the buffer size in `check_so_callback()` but `so_write()` allocates `MAX_STRING_SIZE+1` bytes for its buffer. I would expect these to pass the same sized buffer to `get_CIP_STRING()` since they are both doing the same thing with the result.

I think there has to be a bug here — I suspect the `so_write()` code is wrong since its subsequent comparison `strcmp(rec->val, data)` could never match if the string has to be truncated.

**Comment by kasemir** [comment]
Will a stringin or stringout record hold MAX_STRING_SIZE  (40) characters, or only 39 + '\0'?

get_CIP_STRING will always add a 0, so if the records allow 40 chars, the buffer used with get_CIP_STRING would need 41 chars so it can add the terminator.

**Comment by kasemir** [comment]
A stringin record on the IOC can hold 40 characters:

```
epics> dbpf string  "0....+....1....+....2....+....3....+....4"
DBF_STRING:         "0....+....1....+....2....+....3....+..."         
```

It doesn't need the 40th char to hold a '\0' terminator, it can use all 40 chars for actual text.

In the etherip code, its internal buffer thus needs 41 bytes since it always adds a '\0' byte.
I'll go through and check for consistency.

**Comment by kasemir** [comment]
Sorry, wrong. Confused.
When I try to write 40 chars to a stringin via dbpf as shown above or caput, the record only holds 38 chars.
38 + '\0' would be 39. But the stringin.VAL has room for 40.
So what am I supposed to do in device support

a) Device support can write 40 chars, no '\0' needed.
b) Device support can write 39 chars, plus a required '\0'.
c) Device support can write 38 chars, plus a required '\0', and the 40th element needs to remain unused?

**Comment by kasemir** [comment]
Got a test PLC with strings, will now check with stringin records.

**Comment by anjohnson** [comment]
Your count of 38 above is wrong, your "0" is actually character number 1, "1" is character number 11 etc. I count 39 characters stored like this:
```
epics> dbpf string "12345678901234567890123456789012345678901"
DBF_STRING:         "123456789012345678901234567890123456789"         
```
If I look at the value as a string, I see 40 characters including the trailing zero:
```
tux% caget 'string.$'
string.$ 40 49 50 51 52 53 54 55 56 57 48 49 50 51 52 53 54 55 56 57 48 49 50 51 52 53 54 55 56 57 48 49 50 51 52 53 54 55 56 57 0
```
The "40" at the beginning is the string length, followed by that number of data bytes. Thus the device support should write 39 characters plus the '\0' terminator.

**Comment by kasemir** [comment]
Ah, off by one again, at the very start.

OK, the ether_ip code depends on the string being terminated with '\0', so it can handle a total size of MAX_STRING_SIZE. It enforces that the char at MAX_STRING_SIZE-1 is zero.
I think stringin, stringout and the check for change in stringout are now consistent.

I can use `dbpf` to write "....+....1....+....2....+....3....+....4" to a stringout, and the PLC receives "....+....1....+....2....+....3....+....", and a stringin also reads that back.

So we allow 39 useable chars in the device support.

**Comment by anjohnson** [comment]
I'm sure we fixed this, closing it.
