### ISSUE TITLE
MR testing header issues

### ISSUE THREAD

**Issue by ntanck** [EPICSTools/ether_ip#15]
Hello! I would like to preface by saying that I do understand that this is not exactly supported and definitely a headache, as per commented on ether_ip.c, however, I was trying to get the ReadConnected method on ether_ip_test.c to function as I needed to benchmark some performance differences between multirequests and sequential single requests, and the following problem arises:

With a multirequest that originates from somewhere else other than the test exec directly (such as ones stemming from EPICS ScanLists), there is absolutely no issue at all, the encapsulation header and other related request parts are created OK, but when I try to use the ReadConnected funcion (with and without forward open/close), I get no response (timeout after 5s) and the frame indeed does look different:

Working one: 
0000   00 1d 9c cb 46 b7 ac 1f 6b 40 39 76 08 00 45 00   ....F...k@9v..E.
0010   01 ae ff 42 40 00 40 06 d9 12 0a 00 26 2e 0a 00   ...B@.@.....&...
0020   26 c7 db f0 af 12 5c 47 c7 ea c2 b3 b7 b9 50 18   &.....\G......P.
0030   00 e5 62 95 00 00 6f 00 6e 01 04 00 6c 00 00 00   ..b...o.n...l...
0040   00 00 30 30 42 37 43 44 33 30 00 00 00 00 00 00   ..00B7CD30......
0050   00 00 00 00 02 00 00 00 00 00 b2 00 5e 01 52 02   ............^.R.
0060   20 06 24 01 0a f0 50 01 0a 02 20 02 24 01 06 00    .$...P... .$...
0070   0e 00 46 00 7a 00 ac 00 e4 00 18 01 4c 1a 91 0b   ..F.z.......L... + tags

Generated by ReadConnected:
00000000 70 00 98 01 06 00 24 00 00 00 00 00 30 30 30 30 - p.....$.....0000
00000010 30 30 30 39 00 00 00 00 00 00 00 00 00 00 02 00 - 0009............
00000020 A1 00 04 00 00 00 00 00 B1 00 84 01 01 00 0A 02 - ................
00000030 20 02 24 01 07 00 10 00 48 00 7C 00 AE 00 E6 00 -  .$.....H.|..... + tags

I tried searching for a probable cause on the code so I could restore that functionality just for testing, but I've had poor luck so far. Even if I manage to generate the packet, which I'm sending, it doesn't seem valid as per to incite a response from the PLC.

If necessary, I can provide the modifications I've made in the code, they are mostly related to generating transaction IDs, however,  such as here:

`
```c
static MR_Request *make_SendUnitData (EIPConnection *c, size_t PDU_size, CN_UINT sequence_number)

{
    TransactionID pid;
    EncapsulationUnitData *buf;

    generateTransactionId(&pid);

    if (! make_EncapsulationHeader (c, EC_SendUnitData,
                        (CN_UINT)
                        (offsetof(EncapsulationUnitData, rr)
                          - sizeof (EncapsulationHeader)
                          + PDU_size
                        ), 0, &pid ))
        return 0;
````

If it is not feasible to provide assistance to this feature at this moment, is there a specific reason as to why it was dropped? That could help with determining where exactly the problem is. My goal currently is to receive a response from the multirequest, which is not possible.

Thank you for your attention

**Comment by kasemir** [comment]
Well, I could never find enough documentation to figure out how to read/write 'connected' messages.
At the same time, the 'unconnected' messages worked well enough, so it's been like this for 10+ years.

By now there are some other ethernet/ip libraries out there, so if you don't need something that's connected to EPICS, you might look at those, and maybe they include support for connected messages.

**Comment by ntanck** [comment]
Oh, I understand. I appreciate the quick response! 

I was looking forward to using your solution as it is closer to what's currently in production right now, with the handling of multirequests and such. I don't really mind using unconnected messages, but I was very interested in the multirequest capabilities, as in bunching a bunch of tags into a single request

If I wanted to use this test file to benchmark multirequest times without involving EPICS in the test file, is there any approach I should take or anything that has been done in the past? Since multirequests work with EPICS, would there be a way to emulate that outside it, without its influence? 

I'll also be searching for other libs capable of multirequests, but if you do know any in C/C++, that would really help!

Thanks in advance!

**Comment by ntanck** [comment]
Nevermind, I was able to make it work, I'll check if I can add the changes to a fork. Thanks for the help, however!
