### ISSUE TITLE
Doesn't compile on Windows 10

### ISSUE THREAD

**Issue by devilkingsatan666** [EPICSTools/ether_ip#18]
Dear all,
I was compiling synchrotron apps downloaded with **assemble_synApps** script one can get from [this repo](https://github.com/EPICS-synApps/support) against **EPICS-7.0.5** using plain Windows and the Visual Studio compilers **(2019 community)**, and the compilation failed with the following error:

> gmake[1]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/dxpSITORO-master'
> gmake -C C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3 install
> gmake[1]: Entering directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3'
> gmake -C ./configure install
> gmake[2]: Entering directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/configure'
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/makeMakefile.pl O.windows-x64 ../..
> perl -CSD -MExtUtils::Command -e mkpath O.Common
> gmake -C O.windows-x64 -f ../Makefile TOP=../.. \
>     T_A=windows-x64 install
> gmake[3]: Entering directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/configure/O.windows-x64'
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/convertRelease.pl checkRelease
> gmake[3]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/configure/O.windows-x64'
> gmake[2]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/configure'
> gmake -C ./ether_ipApp install
> gmake[2]: Entering directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp'
> gmake -C ./src install
> gmake[3]: Entering directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp/src'
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/makeMakefile.pl O.windows-x64 ../../..
> perl -CSD -MExtUtils::Command -e mkpath O.Common
> gmake -C O.windows-x64 -f ../Makefile TOP=../../.. \
>     T_A=windows-x64 install
> gmake[4]: Entering directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp/src/O.windows-x64'
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/mkmf.pl  -m drvEtherIPRegister.d -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        drvEtherIPRegister.obj ../drvEtherIPRegister.cpp
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/mkmf.pl  -m devEtherIP.d -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        devEtherIP.obj ../devEtherIP.c
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/mkmf.pl  -m drvEtherIP.d -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        drvEtherIP.obj ../drvEtherIP.c
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/mkmf.pl  -m ether_ip.d -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        ether_ip.obj ../ether_ip.c
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/mkmf.pl  -m dl_list.d -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        dl_list.obj ../dl_list.c
> perl -CSD C:/Users/Ultrafast/EPICS/epics-base/bin/windows-x64/mkmf.pl  -m ether_ip_test.d -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        ether_ip_test.obj ../ether_ip_test.c
> perl -CSD -MExtUtils::Command -e cp ../ether_ip-lsio.dbd ../O.Common/ether_ip.dbd
> "Installing created dbd file ../../../dbd/ether_ip.dbd"
> mkdir ../../../dbd
> "Installing generic include file ../../../include/eip_bool.h"
> mkdir ../../../include
> "Installing generic include file ../../../include/dl_list.h"
> "Installing generic include file ../../../include/ether_ip.h"
> "Installing generic include file ../../../include/drvEtherIP.h"
> cl               -nologo -FC -D__STDC__=0 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE    -Ox -GL -Oy-   -W3     -Wno-unused-value -DUSE_TYPED_RSET -DUSE_TYPED_DSET -DUSE_TYPED_DRVET    -MD -DEPICS_BUILD_DLL -DEPICS_CALL_DLL   -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        -c ../dl_list.c
> cl : Command line error D8021 : invalid numeric argument '/Wno-unused-value'
> gmake[4]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_BUILD:241: dl_list.obj] Error 2
> gmake[4]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp/src/O.windows-x64'
> gmake[3]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_ARCHS:58: install.windows-x64] Error 2
> gmake[3]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp/src'
> gmake[2]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_DIRS:85: src.install] Error 2
> gmake[2]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp'
> gmake[1]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_DIRS:85: ether_ipApp.install] Error 2
> gmake[1]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3'
> gmake: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_DIRS:85: C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3.install] Error 2

I referred to the **EPICS 7** documents [section](https://docs.epics-controls.org/projects/how-tos/en/latest/getting-started/installation-windows-plain.html) for Windows and compiled, but failing on **Windows 10 20H2 (19042.985) x64** using **Visual Studio Community 2019 (16.9.5)** with **C++ Desktop development** tools installed **(v142)**. Any suggestions are appreciated. Thanks in advance for all the replies and your patient reading.

**Comment by devilkingsatan666** [comment]
After commenting out the line specifying that C flag, the compilation still failed with the following error:

> rc -l 0x409 -I. -I../O.Common -I. -I. -I.. -I../../../include/compiler/msvc -I../../../include/os/WIN32 -I../../../include -IC:/Users/Ultrafast/EPICS/epics-base/include/compiler/msvc -IC:/Users/Ultrafast/EPICS/epics-base/include/os/WIN32 -IC:/Users/Ultrafast/EPICS/epics-base/include        -fo ether_ip.res ../ether_ip.rc
> Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> ../ether_ip.rc(5) : error RC2104 : undefined keyword or key name: EPICS_UPDATE_LEVEL
> gmake[4]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_BUILD:254: ether_ip.res] Error 1
> gmake[4]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp/src/O.windows-x64'
> gmake[3]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_ARCHS:58: install.windows-x64] Error 2
> gmake[3]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp/src'
> gmake[2]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_DIRS:85: src.install] Error 2
> gmake[2]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3/ether_ipApp'
> gmake[1]: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_DIRS:85: ether_ipApp.install] Error 2
> gmake[1]: Leaving directory 'C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3'
> gmake: *** [C:/Users/Ultrafast/EPICS/epics-base/configure/RULES_DIRS:85: C:/Users/Ultrafast/EPICS/synApps/support/ether_ip-ether_ip-3-3.install] Error 2

**Comment by kasemir** [comment]
Well, I'm not surprised that there are compilation errors on windows. That `*.rc` file which is only used on windows is 18 years old and very likely out of date. I assume most EPICS sites run IOCs on Linux, where they can conveniently execute as services. IOCs tend to only run on windows if that is necessary because they need to access some hardware which is only supported on windows, typically cameras. So not sure who's around with experience on windows to help here...

**Comment by devilkingsatan666** [comment]
Thank you for your reply. Are there any dependencies this module has with other ones of synchrotron apps? I want to skip this module and compile the rest of the synchrotron apps on windows, but I'm afraid that this module plays a vital role in the application set.

**Comment by kasemir** [comment]
ether_ip only depends on EPICS base, no other synapps modules.

**Comment by devilkingsatan666** [comment]
Is there any module in synchrotron apps, depending on it? It seems that it's safe to skip compiling it on windows. Thank you so much for your reply.

**Comment by devilkingsatan666** [comment]
Since this module is mostly for Linux not Windows, I think it's fine to end the issue here. Thank you for your help.

**Comment by kasemir** [comment]
I agree that it's not a critical issue. Still, at one time (18 years ago ?!) we were able to compile for windows, so if you have time to look into this, by all means do that and let me know about required adjustments, I'd be happy to include them. Thanks for your understanding.
