### ISSUE TITLE
Where to start

### ISSUE THREAD

**Issue by Roboticom314** [EPICSTools/ether_ip#6]
I managed to get the EPICS base to build with the ether_ip module but now I'm having a hard time figuring out how to integrate the rest of my application and where to start. My build produced a library that seems useful (`libether_ip.a/so`). I also see the executables `eipIoc` and `ether_ip_test` of which I believe `eipIoc` is the closest I have to a starting point for a stand-alone application using the libraries/driver. 

I've read through most of http://ics-web.sns.ornl.gov/kasemir/etherip/ for details. I can't seem to find an API document or related open-source examples. 

1. How do the db/dbd (database) files relate to callbacks or calls that I can use in source to read/write the data from C/C++?
2. Is there another GitHub repo of examples that uses this repo?
3. Can I use VisualDCT (http://www.aps.anl.gov/epics/extensions/vdct/) to create the db/dbd files? (if required)
4. Is there API documentation for using the ether_ip library? 
5. Is there any other architecture documentation for the ether_ip library/driver?

Thanks.

**Comment by kasemir** [comment]
See 
https://ics-web.sns.ornl.gov/kasemir/CSS/Training/FRIB/4%20EtherIp.ppt
or the other links at https://ics-web.sns.ornl.gov/kasemir/CSS/Training or EPICS in general
